image: debian/bullseye
packages:
  - git
  - wget
  - protobuf-compiler
  - protoc-gen-go
  - libolm3
  - libolm-dev
secrets:
  - 9ef6e07e-cae5-4ec0-b799-8898de1f742b
sources:
  - ssh://git@git.sr.ht/~aqtrans/gorram
environment:
  project: gorram
triggers:
  - action: email
    condition: failure
    to: Jordan Anderson <jordan@jba.io>
artifacts:
  - gorram/gorram.deb
tasks:
  - setupgo: |
      wget -q https://go.dev/dl/go1.21.3.linux-amd64.tar.gz
      sudo rm -rf /usr/local/go
      sudo tar -C /usr/local -xzf go1.21.3.linux-amd64.tar.gz
      export PATH=$PATH:/usr/local/go/bin
  - setup: |
      export PATH=$PATH:/usr/local/go/bin
      cd ${project}
      export GOBIN=$PWD/bin
      export PATH=$GOBIN:$PATH
      go get -d
      go install github.com/twitchtv/twirp/protoc-gen-twirp
      go install google.golang.org/protobuf/cmd/protoc-gen-go
      go generate
  - test: |
      export PATH=$PATH:/usr/local/go/bin
      cd ${project}
      export GOBIN=$PWD/bin
      export PATH=$GOBIN:$PATH
      go test
      go test -race
      go test -cover
      go test -bench=.
  - build: |
      export PATH=$PATH:/usr/local/go/bin
      cd ${project}
      export GOBIN=$PWD/bin
      export PATH=$GOBIN:$PATH
      go build -ldflags "-X main.sha1ver=$(git rev-parse HEAD) -X main.buildTime=$(date +'%Y-%m-%d_%T')" -o gorram-client ./client
      go build -ldflags "-X main.sha1ver=$(git rev-parse HEAD) -X main.buildTime=$(date +'%Y-%m-%d_%T')" -o gorram-server ./server
      go build -o gorram-cli ./cli
      if [ "$(git rev-parse origin/master)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - buikdpkg: |
      export PATH=$PATH:/usr/local/go/bin
      cd ${project}
      export GOBIN=$PWD/bin
      export PATH=$GOBIN:$PATH
      sudo /bin/bash ./build-pkg.sh $(git rev-parse HEAD)
      cp ./gorram-$(git rev-parse HEAD).deb ./gorram.deb
  - deploy: |
      echo -e "Host B\n         StrictHostKeyChecking no\n    UserKnownHostsFile=/dev/null\n    hostname dev.squanch.space\n    User deploy\n" >> ~/.ssh/config
      echo -e "Host D\n         StrictHostKeyChecking no\n    UserKnownHostsFile=/dev/null\n    hostname rick.lan\n     ProxyJump B\n" >> ~/.ssh/config

      sshopts="ssh -o StrictHostKeyChecking=no"
#      scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./gorram/gorram.deb deploy@D:gorram.deb
#      ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no deploy@D "sudo dpkg -i gorram.deb"
