#!/bin/sh

set -e

USER=gorram

if ! getent passwd "$USER" >/dev/null; then
 adduser --quiet --home /etc/gorram --system "$USER"
fi

systemctl --system daemon-reload >/dev/null
deb-systemd-helper start gorram-server.service >/dev/null 
