#!/bin/sh

set -e

case "$1" in 
    upgrade)
    ;;  
    remove)
        deb-systemd-helper disable gorram-server.service >/dev/null
        deb-systemd-invoke stop gorram-server.service >/dev/null
    ;;
    *)
    ;;
esac

exit 0