secret_key: "omg123"
alert_method: "log"
listen_address: "127.0.0.1:50000"
client1:
    required: true
    interval: 5
    deluge:
        url: "http://127.0.0.1:8112/json"
        password: "password"
        maxtorrents: 5
    diskspace:
        - partition: "/"
          maxusage: 90
        - partition: "/media/storage"
          minfreegb: 20
    loadavg:
        maxload: 2
    geturl:
        - url: "http://google.com"
        - url: "https://some-site.com/health"
          expectedbody: "{\"alive\": true}"
    process:
        - path: "/usr/lib/firefox/firefox"
          user: "username"
        - path: "deluge-gtk"
    memory:
        maxusage: 20
client2:
    interval: 5
    memory:
        maxusage: 15
    diskspace:
        - partition: "/"
          maxusage: 100
    loadavg:
        maxload: 6
client3:
    memory:
        maxusage: 15
