// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gorram.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/gorram.proto

It has these top-level messages:
	PingMsg
	PingResponse
	Submitted
	Issue
	Alert
	ConfigRequest
	Config
	QueryRequest
	ClientList
	Client
	ClientName
	DebugRequest
	DebugResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type PingMsg struct {
	IsAlive        bool  `protobuf:"varint,1,opt,name=is_alive,json=isAlive" json:"is_alive,omitempty"`
	CfgLastUpdated int64 `protobuf:"varint,2,opt,name=cfg_last_updated,json=cfgLastUpdated" json:"cfg_last_updated,omitempty"`
}

func (m *PingMsg) Reset()                    { *m = PingMsg{} }
func (m *PingMsg) String() string            { return proto1.CompactTextString(m) }
func (*PingMsg) ProtoMessage()               {}
func (*PingMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingMsg) GetIsAlive() bool {
	if m != nil {
		return m.IsAlive
	}
	return false
}

func (m *PingMsg) GetCfgLastUpdated() int64 {
	if m != nil {
		return m.CfgLastUpdated
	}
	return 0
}

type PingResponse struct {
	CfgOutOfSync bool `protobuf:"varint,1,opt,name=cfg_out_of_sync,json=cfgOutOfSync" json:"cfg_out_of_sync,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto1.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingResponse) GetCfgOutOfSync() bool {
	if m != nil {
		return m.CfgOutOfSync
	}
	return false
}

type Submitted struct {
	SuccessfullySubmitted bool `protobuf:"varint,1,opt,name=successfully_submitted,json=successfullySubmitted" json:"successfully_submitted,omitempty"`
}

func (m *Submitted) Reset()                    { *m = Submitted{} }
func (m *Submitted) String() string            { return proto1.CompactTextString(m) }
func (*Submitted) ProtoMessage()               {}
func (*Submitted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Submitted) GetSuccessfullySubmitted() bool {
	if m != nil {
		return m.SuccessfullySubmitted
	}
	return false
}

type Issue struct {
	// Host that generated the issue
	// NOTE: THIS SHOULD BE SET BY THE SERVER!
	Host string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	// Title of the check that generated the issue
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	// Message of the issue
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *Issue) Reset()                    { *m = Issue{} }
func (m *Issue) String() string            { return proto1.CompactTextString(m) }
func (*Issue) ProtoMessage()               {}
func (*Issue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Issue) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Issue) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Issue) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Alert struct {
	Issue *Issue `protobuf:"bytes,1,opt,name=issue" json:"issue,omitempty"`
	// When issue was sent
	TimeSubmitted int64 `protobuf:"varint,3,opt,name=time_submitted,json=timeSubmitted" json:"time_submitted,omitempty"`
	// How many times this identical alert has been sent
	Occurrences int64 `protobuf:"varint,4,opt,name=occurrences" json:"occurrences,omitempty"`
}

func (m *Alert) Reset()                    { *m = Alert{} }
func (m *Alert) String() string            { return proto1.CompactTextString(m) }
func (*Alert) ProtoMessage()               {}
func (*Alert) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Alert) GetIssue() *Issue {
	if m != nil {
		return m.Issue
	}
	return nil
}

func (m *Alert) GetTimeSubmitted() int64 {
	if m != nil {
		return m.TimeSubmitted
	}
	return 0
}

func (m *Alert) GetOccurrences() int64 {
	if m != nil {
		return m.Occurrences
	}
	return 0
}

type ConfigRequest struct {
	ClientName string `protobuf:"bytes,1,opt,name=client_name,json=clientName" json:"client_name,omitempty"`
}

func (m *ConfigRequest) Reset()                    { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string            { return proto1.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()               {}
func (*ConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ConfigRequest) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

type Config struct {
	// Used internally to tell when config was last updated
	LastUpdated int64 `protobuf:"varint,1,opt,name=last_updated,json=lastUpdated" json:"last_updated,omitempty"`
	// How often checks should be performed on the client
	Interval int64 `protobuf:"varint,2,opt,name=interval" json:"interval,omitempty"`
	// Configurations for various checks
	Deluge    *Config_Deluge          `protobuf:"bytes,3,opt,name=deluge" json:"deluge,omitempty"`
	Loadavg   *Config_LoadAvg         `protobuf:"bytes,4,opt,name=loadavg" json:"loadavg,omitempty"`
	Diskspace []*Config_DiskSpace     `protobuf:"bytes,5,rep,name=diskspace" json:"diskspace,omitempty"`
	Process   []*Config_ProcessExists `protobuf:"bytes,6,rep,name=process" json:"process,omitempty"`
	GetUrl    []*Config_GetURL        `protobuf:"bytes,7,rep,name=get_url,json=getUrl" json:"get_url,omitempty"`
	// A string of enabled checks
	EnabledChecks string `protobuf:"bytes,8,opt,name=enabled_checks,json=enabledChecks" json:"enabled_checks,omitempty"`
	// Whether client is required to connect
	// Since the server is stateless, this ensures an offline client is detected when the server is restarted
	Required bool             `protobuf:"varint,9,opt,name=required" json:"required,omitempty"`
	Memory   *Config_Memory   `protobuf:"bytes,10,opt,name=memory" json:"memory,omitempty"`
	Postgres *Config_Postgres `protobuf:"bytes,11,opt,name=postgres" json:"postgres,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto1.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Config) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func (m *Config) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *Config) GetDeluge() *Config_Deluge {
	if m != nil {
		return m.Deluge
	}
	return nil
}

func (m *Config) GetLoadavg() *Config_LoadAvg {
	if m != nil {
		return m.Loadavg
	}
	return nil
}

func (m *Config) GetDiskspace() []*Config_DiskSpace {
	if m != nil {
		return m.Diskspace
	}
	return nil
}

func (m *Config) GetProcess() []*Config_ProcessExists {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *Config) GetGetUrl() []*Config_GetURL {
	if m != nil {
		return m.GetUrl
	}
	return nil
}

func (m *Config) GetEnabledChecks() string {
	if m != nil {
		return m.EnabledChecks
	}
	return ""
}

func (m *Config) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *Config) GetMemory() *Config_Memory {
	if m != nil {
		return m.Memory
	}
	return nil
}

func (m *Config) GetPostgres() *Config_Postgres {
	if m != nil {
		return m.Postgres
	}
	return nil
}

type Config_Deluge struct {
	Url         string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	MaxTorrents int64  `protobuf:"varint,3,opt,name=max_torrents,json=maxTorrents" json:"max_torrents,omitempty"`
}

func (m *Config_Deluge) Reset()                    { *m = Config_Deluge{} }
func (m *Config_Deluge) String() string            { return proto1.CompactTextString(m) }
func (*Config_Deluge) ProtoMessage()               {}
func (*Config_Deluge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *Config_Deluge) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Config_Deluge) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Config_Deluge) GetMaxTorrents() int64 {
	if m != nil {
		return m.MaxTorrents
	}
	return 0
}

type Config_LoadAvg struct {
	MaxLoad float64 `protobuf:"fixed64,1,opt,name=max_load,json=maxLoad" json:"max_load,omitempty"`
}

func (m *Config_LoadAvg) Reset()                    { *m = Config_LoadAvg{} }
func (m *Config_LoadAvg) String() string            { return proto1.CompactTextString(m) }
func (*Config_LoadAvg) ProtoMessage()               {}
func (*Config_LoadAvg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 1} }

func (m *Config_LoadAvg) GetMaxLoad() float64 {
	if m != nil {
		return m.MaxLoad
	}
	return 0
}

type Config_DiskSpace struct {
	Partition string  `protobuf:"bytes,1,opt,name=partition" json:"partition,omitempty"`
	MaxUsage  float64 `protobuf:"fixed64,2,opt,name=max_usage,json=maxUsage" json:"max_usage,omitempty"`
	MinFreeGb int64   `protobuf:"varint,3,opt,name=min_free_gb,json=minFreeGb" json:"min_free_gb,omitempty"`
}

func (m *Config_DiskSpace) Reset()                    { *m = Config_DiskSpace{} }
func (m *Config_DiskSpace) String() string            { return proto1.CompactTextString(m) }
func (*Config_DiskSpace) ProtoMessage()               {}
func (*Config_DiskSpace) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 2} }

func (m *Config_DiskSpace) GetPartition() string {
	if m != nil {
		return m.Partition
	}
	return ""
}

func (m *Config_DiskSpace) GetMaxUsage() float64 {
	if m != nil {
		return m.MaxUsage
	}
	return 0
}

func (m *Config_DiskSpace) GetMinFreeGb() int64 {
	if m != nil {
		return m.MinFreeGb
	}
	return 0
}

type Config_ProcessExists struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	User string `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
}

func (m *Config_ProcessExists) Reset()                    { *m = Config_ProcessExists{} }
func (m *Config_ProcessExists) String() string            { return proto1.CompactTextString(m) }
func (*Config_ProcessExists) ProtoMessage()               {}
func (*Config_ProcessExists) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 3} }

func (m *Config_ProcessExists) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Config_ProcessExists) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type Config_GetURL struct {
	Url          string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	ExpectedBody string `protobuf:"bytes,2,opt,name=expected_body,json=expectedBody" json:"expected_body,omitempty"`
}

func (m *Config_GetURL) Reset()                    { *m = Config_GetURL{} }
func (m *Config_GetURL) String() string            { return proto1.CompactTextString(m) }
func (*Config_GetURL) ProtoMessage()               {}
func (*Config_GetURL) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 4} }

func (m *Config_GetURL) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Config_GetURL) GetExpectedBody() string {
	if m != nil {
		return m.ExpectedBody
	}
	return ""
}

type Config_Memory struct {
	MaxUsage float64 `protobuf:"fixed64,1,opt,name=max_usage,json=maxUsage" json:"max_usage,omitempty"`
}

func (m *Config_Memory) Reset()                    { *m = Config_Memory{} }
func (m *Config_Memory) String() string            { return proto1.CompactTextString(m) }
func (*Config_Memory) ProtoMessage()               {}
func (*Config_Memory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 5} }

func (m *Config_Memory) GetMaxUsage() float64 {
	if m != nil {
		return m.MaxUsage
	}
	return 0
}

type Config_Postgres struct {
	ConnectString string `protobuf:"bytes,1,opt,name=connect_string,json=connectString" json:"connect_string,omitempty"`
	ClientAddress string `protobuf:"bytes,2,opt,name=client_address,json=clientAddress" json:"client_address,omitempty"`
}

func (m *Config_Postgres) Reset()                    { *m = Config_Postgres{} }
func (m *Config_Postgres) String() string            { return proto1.CompactTextString(m) }
func (*Config_Postgres) ProtoMessage()               {}
func (*Config_Postgres) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 6} }

func (m *Config_Postgres) GetConnectString() string {
	if m != nil {
		return m.ConnectString
	}
	return ""
}

func (m *Config_Postgres) GetClientAddress() string {
	if m != nil {
		return m.ClientAddress
	}
	return ""
}

type QueryRequest struct {
	// When query was sent
	TimeSubmitted int64 `protobuf:"varint,3,opt,name=time_submitted,json=timeSubmitted" json:"time_submitted,omitempty"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto1.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *QueryRequest) GetTimeSubmitted() int64 {
	if m != nil {
		return m.TimeSubmitted
	}
	return 0
}

type ClientList struct {
	Clients map[string]*Client `protobuf:"bytes,1,rep,name=clients" json:"clients,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ClientList) Reset()                    { *m = ClientList{} }
func (m *ClientList) String() string            { return proto1.CompactTextString(m) }
func (*ClientList) ProtoMessage()               {}
func (*ClientList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ClientList) GetClients() map[string]*Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

type Client struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Address      string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	LastPingTime int64  `protobuf:"varint,3,opt,name=last_ping_time,json=lastPingTime" json:"last_ping_time,omitempty"`
}

func (m *Client) Reset()                    { *m = Client{} }
func (m *Client) String() string            { return proto1.CompactTextString(m) }
func (*Client) ProtoMessage()               {}
func (*Client) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Client) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Client) GetLastPingTime() int64 {
	if m != nil {
		return m.LastPingTime
	}
	return 0
}

type ClientName struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ClientName) Reset()                    { *m = ClientName{} }
func (m *ClientName) String() string            { return proto1.CompactTextString(m) }
func (*ClientName) ProtoMessage()               {}
func (*ClientName) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ClientName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DebugRequest struct {
	Debug bool `protobuf:"varint,1,opt,name=debug" json:"debug,omitempty"`
}

func (m *DebugRequest) Reset()                    { *m = DebugRequest{} }
func (m *DebugRequest) String() string            { return proto1.CompactTextString(m) }
func (*DebugRequest) ProtoMessage()               {}
func (*DebugRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DebugRequest) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

type DebugResponse struct {
	Resp string `protobuf:"bytes,1,opt,name=resp" json:"resp,omitempty"`
}

func (m *DebugResponse) Reset()                    { *m = DebugResponse{} }
func (m *DebugResponse) String() string            { return proto1.CompactTextString(m) }
func (*DebugResponse) ProtoMessage()               {}
func (*DebugResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *DebugResponse) GetResp() string {
	if m != nil {
		return m.Resp
	}
	return ""
}

func init() {
	proto1.RegisterType((*PingMsg)(nil), "proto.PingMsg")
	proto1.RegisterType((*PingResponse)(nil), "proto.PingResponse")
	proto1.RegisterType((*Submitted)(nil), "proto.Submitted")
	proto1.RegisterType((*Issue)(nil), "proto.Issue")
	proto1.RegisterType((*Alert)(nil), "proto.Alert")
	proto1.RegisterType((*ConfigRequest)(nil), "proto.ConfigRequest")
	proto1.RegisterType((*Config)(nil), "proto.Config")
	proto1.RegisterType((*Config_Deluge)(nil), "proto.Config.Deluge")
	proto1.RegisterType((*Config_LoadAvg)(nil), "proto.Config.LoadAvg")
	proto1.RegisterType((*Config_DiskSpace)(nil), "proto.Config.DiskSpace")
	proto1.RegisterType((*Config_ProcessExists)(nil), "proto.Config.ProcessExists")
	proto1.RegisterType((*Config_GetURL)(nil), "proto.Config.GetURL")
	proto1.RegisterType((*Config_Memory)(nil), "proto.Config.Memory")
	proto1.RegisterType((*Config_Postgres)(nil), "proto.Config.Postgres")
	proto1.RegisterType((*QueryRequest)(nil), "proto.QueryRequest")
	proto1.RegisterType((*ClientList)(nil), "proto.ClientList")
	proto1.RegisterType((*Client)(nil), "proto.Client")
	proto1.RegisterType((*ClientName)(nil), "proto.ClientName")
	proto1.RegisterType((*DebugRequest)(nil), "proto.DebugRequest")
	proto1.RegisterType((*DebugResponse)(nil), "proto.DebugResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Reporter service

type ReporterClient interface {
	// Hello should be called once upon initial connection. It syncs the config and stops any timers
	Hello(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*Config, error)
	// Ping is a heartbeat check, ran every X seconds to ensure a client is still alive
	// The cfg_last_updated variable sent, and cfg_out_of_sync received also allow syncing the config
	Ping(ctx context.Context, in *PingMsg, opts ...grpc.CallOption) (*PingResponse, error)
	RecordIssue(ctx context.Context, opts ...grpc.CallOption) (Reporter_RecordIssueClient, error)
	ConfigSync(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*Config, error)
}

type reporterClient struct {
	cc *grpc.ClientConn
}

func NewReporterClient(cc *grpc.ClientConn) ReporterClient {
	return &reporterClient{cc}
}

func (c *reporterClient) Hello(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := grpc.Invoke(ctx, "/proto.Reporter/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) Ping(ctx context.Context, in *PingMsg, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/proto.Reporter/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) RecordIssue(ctx context.Context, opts ...grpc.CallOption) (Reporter_RecordIssueClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Reporter_serviceDesc.Streams[0], c.cc, "/proto.Reporter/RecordIssue", opts...)
	if err != nil {
		return nil, err
	}
	x := &reporterRecordIssueClient{stream}
	return x, nil
}

type Reporter_RecordIssueClient interface {
	Send(*Issue) error
	CloseAndRecv() (*Submitted, error)
	grpc.ClientStream
}

type reporterRecordIssueClient struct {
	grpc.ClientStream
}

func (x *reporterRecordIssueClient) Send(m *Issue) error {
	return x.ClientStream.SendMsg(m)
}

func (x *reporterRecordIssueClient) CloseAndRecv() (*Submitted, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Submitted)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *reporterClient) ConfigSync(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := grpc.Invoke(ctx, "/proto.Reporter/ConfigSync", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Reporter service

type ReporterServer interface {
	// Hello should be called once upon initial connection. It syncs the config and stops any timers
	Hello(context.Context, *ConfigRequest) (*Config, error)
	// Ping is a heartbeat check, ran every X seconds to ensure a client is still alive
	// The cfg_last_updated variable sent, and cfg_out_of_sync received also allow syncing the config
	Ping(context.Context, *PingMsg) (*PingResponse, error)
	RecordIssue(Reporter_RecordIssueServer) error
	ConfigSync(context.Context, *ConfigRequest) (*Config, error)
}

func RegisterReporterServer(s *grpc.Server, srv ReporterServer) {
	s.RegisterService(&_Reporter_serviceDesc, srv)
}

func _Reporter_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Reporter/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).Hello(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Reporter/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).Ping(ctx, req.(*PingMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_RecordIssue_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReporterServer).RecordIssue(&reporterRecordIssueServer{stream})
}

type Reporter_RecordIssueServer interface {
	SendAndClose(*Submitted) error
	Recv() (*Issue, error)
	grpc.ServerStream
}

type reporterRecordIssueServer struct {
	grpc.ServerStream
}

func (x *reporterRecordIssueServer) SendAndClose(m *Submitted) error {
	return x.ServerStream.SendMsg(m)
}

func (x *reporterRecordIssueServer) Recv() (*Issue, error) {
	m := new(Issue)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Reporter_ConfigSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).ConfigSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Reporter/ConfigSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).ConfigSync(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reporter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Reporter",
	HandlerType: (*ReporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Reporter_Hello_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Reporter_Ping_Handler,
		},
		{
			MethodName: "ConfigSync",
			Handler:    _Reporter_ConfigSync_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RecordIssue",
			Handler:       _Reporter_RecordIssue_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/gorram.proto",
}

// Client API for Querier service

type QuerierClient interface {
	List(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ClientList, error)
	Delete(ctx context.Context, in *ClientName, opts ...grpc.CallOption) (*ClientList, error)
	Debug(ctx context.Context, in *DebugRequest, opts ...grpc.CallOption) (*DebugResponse, error)
}

type querierClient struct {
	cc *grpc.ClientConn
}

func NewQuerierClient(cc *grpc.ClientConn) QuerierClient {
	return &querierClient{cc}
}

func (c *querierClient) List(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ClientList, error) {
	out := new(ClientList)
	err := grpc.Invoke(ctx, "/proto.Querier/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *querierClient) Delete(ctx context.Context, in *ClientName, opts ...grpc.CallOption) (*ClientList, error) {
	out := new(ClientList)
	err := grpc.Invoke(ctx, "/proto.Querier/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *querierClient) Debug(ctx context.Context, in *DebugRequest, opts ...grpc.CallOption) (*DebugResponse, error) {
	out := new(DebugResponse)
	err := grpc.Invoke(ctx, "/proto.Querier/Debug", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Querier service

type QuerierServer interface {
	List(context.Context, *QueryRequest) (*ClientList, error)
	Delete(context.Context, *ClientName) (*ClientList, error)
	Debug(context.Context, *DebugRequest) (*DebugResponse, error)
}

func RegisterQuerierServer(s *grpc.Server, srv QuerierServer) {
	s.RegisterService(&_Querier_serviceDesc, srv)
}

func _Querier_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Querier/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierServer).List(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Querier_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Querier/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierServer).Delete(ctx, req.(*ClientName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Querier_Debug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierServer).Debug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Querier/Debug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierServer).Debug(ctx, req.(*DebugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Querier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Querier",
	HandlerType: (*QuerierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Querier_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Querier_Delete_Handler,
		},
		{
			MethodName: "Debug",
			Handler:    _Querier_Debug_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gorram.proto",
}

func init() { proto1.RegisterFile("proto/gorram.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1073 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0x8e, 0x93, 0xec, 0x7a, 0xf7, 0x78, 0x37, 0x84, 0x21, 0x2d, 0xc6, 0x45, 0x25, 0x38, 0x89,
	0x94, 0x0b, 0x9a, 0x86, 0x2d, 0x11, 0x15, 0x37, 0x28, 0x4d, 0x4b, 0xa9, 0x48, 0x7f, 0x70, 0x1a,
	0x09, 0x24, 0x24, 0xcb, 0x6b, 0x9f, 0x75, 0x46, 0xb1, 0x3d, 0xee, 0xcc, 0x38, 0x64, 0x1f, 0x83,
	0x67, 0xe0, 0x75, 0xb8, 0xe1, 0x8d, 0xd0, 0xfc, 0x78, 0xb3, 0x0e, 0xb9, 0xe8, 0x95, 0xe7, 0x7c,
	0xe7, 0x6f, 0xce, 0xf9, 0x8e, 0xcf, 0x00, 0xa9, 0x39, 0x93, 0xec, 0x71, 0xce, 0x38, 0x4f, 0xca,
	0x03, 0x2d, 0x90, 0x9e, 0xfe, 0x84, 0x6f, 0xc0, 0x7d, 0x47, 0xab, 0xfc, 0xb5, 0xc8, 0xc9, 0x17,
	0x30, 0xa0, 0x22, 0x4e, 0x0a, 0x7a, 0x85, 0xbe, 0xb3, 0xed, 0xec, 0x0f, 0x22, 0x97, 0x8a, 0x63,
	0x25, 0x92, 0x7d, 0xd8, 0x4c, 0x67, 0x79, 0x5c, 0x24, 0x42, 0xc6, 0x4d, 0x9d, 0x25, 0x12, 0x33,
	0x7f, 0x75, 0xdb, 0xd9, 0x5f, 0x8b, 0x36, 0xd2, 0x59, 0x7e, 0x9a, 0x08, 0x79, 0x6e, 0xd0, 0xf0,
	0x08, 0x46, 0x2a, 0x5e, 0x84, 0xa2, 0x66, 0x95, 0x40, 0xb2, 0x07, 0x9f, 0x28, 0x4f, 0xd6, 0xc8,
	0x98, 0xcd, 0x62, 0x31, 0xaf, 0x52, 0x1b, 0x7b, 0x94, 0xce, 0xf2, 0xb7, 0x8d, 0x7c, 0x3b, 0x3b,
	0x9b, 0x57, 0x69, 0xf8, 0x0c, 0x86, 0x67, 0xcd, 0xb4, 0xa4, 0x52, 0x62, 0x46, 0x8e, 0xe0, 0xbe,
	0x68, 0xd2, 0x14, 0x85, 0x98, 0x35, 0x45, 0x31, 0x8f, 0x45, 0xab, 0xb1, 0xae, 0xf7, 0x96, 0xb5,
	0x0b, 0xb7, 0xf0, 0x17, 0xe8, 0xbd, 0x12, 0xa2, 0x41, 0x42, 0x60, 0xfd, 0x82, 0x09, 0xa9, 0xad,
	0x87, 0x91, 0x3e, 0x93, 0x2d, 0xe8, 0x49, 0x2a, 0x0b, 0xd4, 0xd7, 0x1e, 0x46, 0x46, 0x20, 0x3e,
	0xb8, 0x25, 0x0a, 0x91, 0xe4, 0xe8, 0xaf, 0x69, 0xbc, 0x15, 0x43, 0x09, 0xbd, 0xe3, 0x02, 0xb9,
	0x24, 0x21, 0xf4, 0xa8, 0x8a, 0xaa, 0xa3, 0x79, 0x93, 0x91, 0x69, 0xdf, 0x81, 0xce, 0x14, 0x19,
	0x15, 0xd9, 0x83, 0x0d, 0x49, 0x4b, 0x5c, 0xba, 0xe8, 0x9a, 0x6e, 0xce, 0x58, 0xa1, 0x37, 0x75,
	0x6d, 0x83, 0xc7, 0xd2, 0xb4, 0xe1, 0x1c, 0xab, 0x14, 0x85, 0xbf, 0xae, 0x6d, 0x96, 0xa1, 0xf0,
	0x10, 0xc6, 0x27, 0xac, 0x9a, 0xd1, 0x3c, 0xc2, 0x0f, 0x0d, 0x0a, 0x49, 0xbe, 0x02, 0x2f, 0x2d,
	0x28, 0x56, 0x32, 0xae, 0x92, 0x12, 0x6d, 0x45, 0x60, 0xa0, 0x37, 0x49, 0x89, 0xe1, 0x3f, 0x2e,
	0xf4, 0x8d, 0x0b, 0xf9, 0x1a, 0x46, 0x1d, 0x82, 0x1c, 0x13, 0xbf, 0xb8, 0x61, 0x87, 0x04, 0x30,
	0xa0, 0x95, 0x44, 0x7e, 0x95, 0x14, 0x96, 0xbf, 0x85, 0x4c, 0xbe, 0x81, 0x7e, 0x86, 0x45, 0x63,
	0x5b, 0xe1, 0x4d, 0xb6, 0x6c, 0xa5, 0x26, 0xfa, 0xc1, 0x73, 0xad, 0x8b, 0xac, 0x0d, 0x79, 0x0c,
	0x6e, 0xc1, 0x92, 0x2c, 0xb9, 0xca, 0x75, 0x1d, 0xde, 0xe4, 0x5e, 0xd7, 0xfc, 0x94, 0x25, 0xd9,
	0xf1, 0x55, 0x1e, 0xb5, 0x56, 0xe4, 0x08, 0x86, 0x19, 0x15, 0x97, 0xa2, 0x4e, 0x52, 0xf4, 0x7b,
	0xdb, 0x6b, 0xfb, 0xde, 0xe4, 0xf3, 0x5b, 0x19, 0xa8, 0xb8, 0x3c, 0x53, 0xea, 0xe8, 0xc6, 0x92,
	0x1c, 0x81, 0x5b, 0x73, 0xa6, 0xd8, 0xf6, 0xfb, 0xda, 0xe9, 0x41, 0xd7, 0xe9, 0x9d, 0x51, 0xbe,
	0xb8, 0xa6, 0x42, 0x8a, 0xa8, 0xb5, 0x25, 0x8f, 0xc0, 0xcd, 0x51, 0xc6, 0x0d, 0x2f, 0x7c, 0x57,
	0xbb, 0xdd, 0xaa, 0xe6, 0x25, 0xca, 0xf3, 0xe8, 0x34, 0xea, 0xe7, 0x28, 0xcf, 0x79, 0xa1, 0x08,
	0xc4, 0x2a, 0x99, 0x16, 0x98, 0xc5, 0xe9, 0x05, 0xa6, 0x97, 0xc2, 0x1f, 0xe8, 0x4e, 0x8f, 0x2d,
	0x7a, 0xa2, 0x41, 0xd5, 0x3e, 0x8e, 0x1f, 0x1a, 0xca, 0x31, 0xf3, 0x87, 0x7a, 0x14, 0x17, 0xb2,
	0x6a, 0x5f, 0x89, 0x25, 0xe3, 0x73, 0x1f, 0xee, 0x6a, 0xdf, 0x6b, 0xad, 0x8b, 0xac, 0x0d, 0x99,
	0xc0, 0xa0, 0x66, 0x42, 0xe6, 0x1c, 0x85, 0xef, 0x69, 0xfb, 0xfb, 0xb7, 0xea, 0xb2, 0xda, 0x68,
	0x61, 0x17, 0xfc, 0x0e, 0x7d, 0x43, 0x02, 0xd9, 0x84, 0x35, 0x55, 0x99, 0x99, 0x06, 0x75, 0x54,
	0x37, 0xab, 0x13, 0x21, 0xfe, 0x64, 0x3c, 0xb3, 0x13, 0xbe, 0x90, 0xd5, 0x5c, 0x94, 0xc9, 0x75,
	0x2c, 0x99, 0x9a, 0x32, 0x29, 0xec, 0x6c, 0x7a, 0x65, 0x72, 0xfd, 0xde, 0x42, 0xc1, 0x2e, 0xb8,
	0x96, 0x30, 0xb5, 0x05, 0x94, 0xb5, 0xa2, 0x4d, 0x27, 0x70, 0x22, 0xb7, 0x4c, 0xae, 0x95, 0x36,
	0x98, 0xc1, 0x70, 0xc1, 0x11, 0xf9, 0x12, 0x86, 0x75, 0xc2, 0x25, 0x95, 0x94, 0x55, 0xf6, 0x26,
	0x37, 0x00, 0x79, 0x00, 0x43, 0x15, 0xa5, 0xd1, 0xbf, 0xd6, 0xaa, 0x0e, 0xa3, 0xc2, 0x9e, 0x2b,
	0x99, 0x3c, 0x04, 0xaf, 0xa4, 0x55, 0x3c, 0xe3, 0x88, 0x71, 0x3e, 0xb5, 0xf7, 0x19, 0x96, 0xb4,
	0xfa, 0x89, 0x23, 0xbe, 0x9c, 0x06, 0xdf, 0xc3, 0xb8, 0x43, 0xab, 0xfa, 0xa1, 0xeb, 0x44, 0x5e,
	0xb4, 0x3f, 0xb4, 0x3a, 0x2b, 0xac, 0x11, 0xc8, 0x6d, 0xb5, 0xfa, 0x1c, 0xfc, 0x08, 0x7d, 0x43,
	0xec, 0x1d, 0x1d, 0xda, 0x81, 0x31, 0x5e, 0xd7, 0x98, 0x4a, 0xcc, 0xe2, 0x29, 0xcb, 0xe6, 0xd6,
	0x71, 0xd4, 0x82, 0xcf, 0x58, 0x36, 0x0f, 0xf6, 0xa0, 0x6f, 0x88, 0xea, 0x16, 0xe0, 0x74, 0x0b,
	0x08, 0x7e, 0x83, 0x41, 0xcb, 0x8f, 0x1a, 0x9d, 0x94, 0x55, 0x15, 0xa6, 0x32, 0x16, 0x92, 0xd3,
	0x2a, 0xb7, 0x49, 0xc7, 0x16, 0x3d, 0xd3, 0xa0, 0x36, 0x33, 0x3f, 0x72, 0x92, 0x65, 0x5c, 0x8d,
	0xf3, 0xaa, 0x35, 0xd3, 0xe8, 0xb1, 0x01, 0xd5, 0xfa, 0xfc, 0xb5, 0x41, 0x3e, 0x6f, 0xff, 0xff,
	0x8f, 0xdb, 0x2c, 0xe1, 0x5f, 0x0e, 0xc0, 0x89, 0x0e, 0x74, 0x4a, 0x85, 0x24, 0x4f, 0xc1, 0x35,
	0x61, 0x85, 0xef, 0xe8, 0xe9, 0x7f, 0xd8, 0x0e, 0xd7, 0xc2, 0xc6, 0x1e, 0xc5, 0x8b, 0x4a, 0xf2,
	0x79, 0xd4, 0x9a, 0x07, 0xaf, 0x60, 0xb4, 0xac, 0x50, 0x7d, 0xbc, 0xc4, 0x79, 0xdb, 0xc7, 0x4b,
	0x9c, 0x93, 0x1d, 0xe8, 0x5d, 0x25, 0x45, 0x63, 0x58, 0xf5, 0x26, 0xe3, 0x4e, 0xe4, 0xc8, 0xe8,
	0x7e, 0x58, 0x7d, 0xea, 0x84, 0x7f, 0x40, 0xdf, 0x80, 0x8a, 0xaa, 0xa5, 0xed, 0xa5, 0xcf, 0x6a,
	0xf3, 0x76, 0x1b, 0xd1, 0x8a, 0x64, 0x17, 0x36, 0xf4, 0x1a, 0xab, 0x69, 0x95, 0xc7, 0xaa, 0x4c,
	0x5b, 0xb2, 0x5e, 0x6e, 0xea, 0x6d, 0x79, 0x4f, 0x4b, 0x0c, 0xb7, 0xdb, 0x82, 0xd5, 0x16, 0xbc,
	0x2b, 0x43, 0xb8, 0x0b, 0xa3, 0xe7, 0x38, 0x6d, 0x16, 0xab, 0x74, 0x0b, 0x7a, 0x99, 0x92, 0xed,
	0x23, 0x62, 0x84, 0x70, 0x07, 0xc6, 0xd6, 0xca, 0x3e, 0x58, 0x04, 0xd6, 0x39, 0x8a, 0xba, 0x0d,
	0xa5, 0xce, 0x93, 0x7f, 0x1d, 0x18, 0x44, 0x58, 0x33, 0x2e, 0x91, 0x93, 0x03, 0xe8, 0xfd, 0x8c,
	0x45, 0xc1, 0x48, 0xf7, 0x0f, 0xb7, 0x69, 0x82, 0x71, 0x07, 0x0d, 0x57, 0xc8, 0x23, 0x58, 0x57,
	0xb7, 0x26, 0x1b, 0x56, 0x61, 0x9f, 0xdb, 0xe0, 0xb3, 0x25, 0xb9, 0xcd, 0x1e, 0xae, 0x90, 0x6f,
	0xc1, 0x8b, 0x30, 0x65, 0x3c, 0x33, 0x6f, 0x59, 0xe7, 0xbd, 0x09, 0x36, 0xad, 0x74, 0xc3, 0xfc,
	0xca, 0xbe, 0x43, 0x9e, 0x00, 0x98, 0x6c, 0xea, 0x29, 0xfd, 0xc8, 0x6b, 0x4d, 0xfe, 0x76, 0xc0,
	0x55, 0xa3, 0x46, 0x91, 0x93, 0x43, 0x58, 0xd7, 0x73, 0xd3, 0x5e, 0x69, 0x79, 0x04, 0x83, 0x4f,
	0xff, 0x37, 0x3b, 0xe1, 0x0a, 0x39, 0xd4, 0xbb, 0x08, 0x25, 0x92, 0xae, 0x5a, 0xb1, 0x71, 0xb7,
	0xc7, 0x77, 0xd0, 0xd3, 0x8d, 0x5e, 0x24, 0x59, 0x26, 0x27, 0xd8, 0xea, 0x82, 0x6d, 0x37, 0xa6,
	0x7d, 0x0d, 0x3f, 0xf9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x07, 0x83, 0xdd, 0x11, 0xc2, 0x08, 0x00,
	0x00,
}
